# Generated by Django 3.2.8 on 2021-10-07 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(blank=True, max_length=255, null=True)),
                ('resource_url', models.CharField(blank=True, max_length=255, null=True)),
                ('top_tag', models.CharField(max_length=255)),
                ('bottom_tag', models.CharField(max_length=255)),
                ('title_cut', models.CharField(max_length=255)),
                ('date_cut', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('nd_date', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('s_date', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('not_date', models.DateField()),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.resourse')),
            ],
        ),
    ]
